### ISSUE TITLE
Train of Thought Review

### ISSUE THREAD

**Issue by timoxley** [jesstelford/esnext-generation#1]
Thanks for getting this going @jesstelford!

Brace yourself, I'm about to get nit-picky. Nothing personal of course, and I'm willing to admit I may be off the mark or flat out wrong! Don't be discouraged because this is a great workshop already, even if you disregard all of my comments I'm very proud to be able to present this to attendees at CampJS V.

From here on out I'm just logging my thoughts as I think them:
- `esnext-generation` is a long one to type, maybe could include a shorter alias to binary.
- node/iojs prerequisite could/should be enforced
#1. Traditional Looping
- Not sure the purpose of this exercise, I guess it's to ensure people understand basic iteration before diving into the more advanced iteration. Perhaps is a bit too basic for all but the most green JS developers.
- "Looping" vs "Iterating" vs "Enumerating" vs "Sequences". Is a `.forEach` really a "loop"? IMO loops are specifically while/for/do..while language constructs, while `.forEach` is not a loop, but all of these enable iteration/enumeration, which I haven't found a useful distinction for yet and are synonyms. This is just how I categorise these features in my head and is by no means canonical definition.

> Over time the language has expanded to contain further looping constructs to cover Objects and Arrays:

vs

> JavaScript has evolved to include more convenient features for iterating over its built-in collection datatypes:
- The `## Object` & `## Array` headings could be more explicit, something like:
  `## Looping over Object values using for...in`
  `## Looping over Array values using forEach`
- The `Array` section could be more meaty. Maybe you could explicitly point out that "you shouldn't use `for...in` to enumerate arrays" as this is a common stumbling block rather than just 
- "requiring a special function `Array.prototype.forEach(function(){})`"
  If someone needs to be taught about `forEach` vs `for` there's a good chance they won't understand the `Array.prototype.*` notation.
- "Complete the following boilerplate"
  Maybe be more explicit: "copy this boilerplate to a new file and complete with your solution:"
- From a functional programming perspective, an example exercise of "find a single value from a set of values" isn't the best usage for `.forEach` – since this operation would be better described by a `reduce`… IMO. I usually reserve `.forEach` for things with external side effects for each item, and `for` for cases where I don't know the number of iterations up-front (e.g. constructing a new Array) or for performance. 
- Your solution won't handle negative numbers because of `var largest = 0;`. Use `var largest = -Infinity;` instead.
### My Solution:

``` js
module.exports = function max(arr) {
  return arr.reduce(function(max, cur) { return Math.max(max, cur) })
}
```
#2. Introduction To Iterators
- "es6 (aka ESNext)" AFAIK it's not called either of these things any more. It's ES2015. Also consider always capitalizing.
- What do you mean by "finally"
- Consider a line break after ""Iterators are nothing more than objects with a certain interface."[1]
- This syntax is likely unfamiliar to many `next() -> {value: <mixed>, done: <boolean>}`, perhaps include an "in english" translation: "That interface consists of a single method: "next", which takes no arguments (not true???) and returns an object containing a `value` property of any type, and `done` flag:"
- "While Iterators may appear overly verbose" might be best to not assume what the reader is thinking as it can shape their attitude towards using the interface.
- "Create a function, count(), which returns an Iterator that returns the numbers 1, 2, 3, ... etc, up to 10."  Starting at zero? Maybe s/numbers/positive integers.
- Maybe get people to write out the full iterator interface, just give them an object hash, since it's trivial and maybe drives home the point that "Iterators" are just POJOs with a particular flavour of `next`.
- Note that real-world iterators often throw away the `value` when `done` is true, so this might be setting people up for surprises later, though perhaps you're going to cover this in a future exercise.
- I ignored the bonus points, don't want to be known as "[teacher's pet](http://www.urbandictionary.com/define.php?term=Teacher%27s+pet&defid=7097197)"
## My Solution

``` js
module.exports = function count() {
  var i = 0
  return {
    next: function() {
      i++
      return {
        value: i,
        done: !(i <= 10)
      }
    }
  }
}
```
#3. Built In Iterators
- I believe "Built In" should be hyphenated when used as an adjective.
- "Es6" at the start of a sentence looks weird against "es6" in the middle of a sentence. Again, I suggest capitalisation.
- "have an iterator" and "provide built in iterators" isn't really right, more correct would be "implements Iterable interface".
- I suggest flipping the order that you explain things i.e. explain what we've been creating are "iterators" then explain what the "iterable interface" is and that this makes these collection instances "iterables", thus usable with `for...of`
- Might be worth introducing [well-known Symbols](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols)
- "Arrays, Objects, and the new es6 Map & Set collections all provide built in iterators"`Objects don't: Object.prototype[Symbol.iterator] === undefined` but `TypedArray` does (and so does `Buffer` in iojs).
- "not to be confused with looping over objects" -> "not to be confused with looping over objects values with for...in"
- `for(... in ...){}`: I suggest standardising on [MDN syntax of `for...in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)
- "Rewrite your function, max(), from Traditional Looping" Oops I wrote over it.
- I suggest the exercise does something like pass the user both a `Set` and an `Array` objects and have them use the `for...of` interface to iterate over them. i.e. demonstrate "universality" of the interface, so long as thing is iterable you can treat them the same.
- perhaps change `collection` in boilerplate to `iterable` to be explicit
- Perhaps detect global pollution as people often forget they need to use `var`/`let` in `for...in`/`for...of`
## My Solution

``` js
module.exports = function max(collection) {
  var currentMax = -Infinity
  for (var num of collection) {
    currentMax = Math.max(currentMax, num)
  }
  return currentMax
}
```
#4. Advanced Iterables
- "Iteratabls specificatoin:"
- "ie;" [i.e.](http://en.wiktionary.org/wiki/i.e.)
- "Both the function which creates the Iterable (max() in Introduction To Iterators)" Introduction to Iterators was `count` not `max` and it created Iterator instances, but it wasn't Iterable itself: "In order to be iterable, an object must implement the @@iterator method" [source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_.22iterable.22_protocol)
- Perhaps also try to encourage understanding that the Iterator interface can and should be used to represent _any_ type of sequence, even infinite sequences. Gives us a unified interface for to defining both abstract sequences and abstract operations which work with sequences.
- Your verification insists that `done:false` exists, but [the `done` key is optional and considered `false` if non-existent](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-iteratorresult-interface).
- Not sure this exercise is any more advanced than the "Introduction To Iterators" exercise since we're just passing in regular function arguments to a regular function. You mention passing values to next, but we don't do that. Suggest maybe force people to set the start & end values in "Introduction To Iterators", then maybe have this one only require "start". These may be way too easy though. Consumption of an infinite iterator might be more interesting, perhaps you could do something like have them implement "pluck" or "take" i.e. pass them an infinite iterator and a number "total", then have them produce a new iterator that consumes the first iterator until "total" number of items have been iterated or the iterator is exhausted. That's not at all hard but gets them thinking about infinite sequences and how to write utilities that produce and consume iterators rather than arrays.
- `var num, done = false;` IMO manually hoisting variables is an unnecessary anachronism, I avoid this as it runs high risk of creating unused variables. Your code has fallen victim to this.
- `var num, done = false;`  Chained var statements also blegh, as it creates high risk of accidental globals and is a pain in the ass to reorder. IMO.
## My Solution

``` js
module.exports = function generate(isEven) {
  var start = isEven ? 0 : -1
  return {
    next: function() {
      return {
        value: start += 2,
        done: false // should not be required
      }
    }
  }
}
```

**Sorry, I don't have time now to do the last two exercises right now, I'll try to get to them this week.**
## Overall

I may have lots of comments but I do this is a great-looking workshop! I can see where you're going with these exercises and I like it. It's nice and gentle. You explain the concepts well, in a good sequence + link to all the appropriate information. Great job!

**Comment by jesstelford** [comment]
Thanks so much for your awesome feedback @timoxley! I'm going to split my responses up into two sections: First where I have outstanding questions, then second where I go through and fix a lot of the bits and pieces you pointed out.

## Outstanding Questions

> node/iojs prerequisite could/should be enforced

I've added an `engineStrict` directive to `package.json`, but it [looks like it'll be deprecated](https://docs.npmjs.com/files/package.json#enginestrict) in the near future. 83b5aa4

I was thinking: Is it possible to maybe use `babel-node` to transpile the code before execution when we detect node < 0.11.4?

### 3. Built in iterators

> I suggest flipping the order that you explain [iterators & for...of]

Since I merged the "traditional looping" lesson into this one, I think it flows better as "forEach -> for...in -> for...of -> example". What do you think?

> I suggest the exercise does something like [...] demonstrate "universality" of the interface. [...] perhaps change `collection` in boilerplate to `iterable` to be explicit

Good point. I've extended it a bit further to be:

```
Write a function `filterForNumbers(iterable)` which extracts only the numeric
values from `iterable`, returning those values as an Array. `iterable` could be
any built-in Iterable, or a custom Iterable exposing an Iterator via the key
`Symbol.iterator`.

Copy this boilerplate to a new file and complete with your solution, then
execute `$ADVENTURE_COMMAND verify <your-file.js>` to verify it.

module.exports = function filterForNumbers(iterable) {
  // loop over iterable, adding numeric valus to a new array
  // then return the new array of numbers
}
```

I think this drives home the point that any Iterable can be iterated via `for...of`. Let me know if you think it can be enhanced further.

> Perhaps detect global pollution as people often forget they need to use `var`/`let` in `for...in`/`for...of`

Hmm, I just checked using `Object.keys` on `global`, and it appears there are other globals which get added (`_` being one):

``` bash
$ node
> Object.keys(global);
[ 'global',
  'process',
  'GLOBAL',
  'root',
  'Buffer',
  'setTimeout',
  'setInterval',
  'clearTimeout',
  'clearInterval',
  'setImmediate',
  'clearImmediate',
  'console',
  'module',
  'require' ]
> for(foo in [1, 2, 3]){ console.log(foo); }
0
1
2
undefined
> Object.keys(global);
[ 'global',
  'process',
  'GLOBAL',
  'root',
  'Buffer',
  'setTimeout',
  'setInterval',
  'clearTimeout',
  'clearInterval',
  'setImmediate',
  'clearImmediate',
  'console',
  'module',
  'require',
  '_',
  'foo' ]
```

Do you know of any other ways to detect global leakage? Or, maybe I need to warm the globals by using for...of once before testing? That seems like it might be brittle, though :(

### 4. Advanced Iterables

> Not sure this exercise is any more advanced than the "Introduction To Iterators" exercise

Yep, agreed. My main goal was to act as the bridge to generators in the next lesson. Essentially introducing the idea that we can `generate()` Iterators that do particular things.

Later on, there is an entire lesson dedicated to passing values to `.next()` via `yield` in generators. I also point this out in the `Extra Credit` section of the `Advanced Iterators` lesson.

... Actually, I've gone ahead and enforced accepting a value to `.next()`, and made the _Extra Credit_ section about plucking from an infinite Iterable: c7c1eec. Thoughts?

## Bits & Pieces Fixes

> `esnext-generation` is a long one to type, maybe could include a shorter alias to binary.

Good call! I added `esng` as an alias. It doesn't seem to be a command in use on Linux or OSX. 26d9d57

> "Looping" vs "Iterating" vs "Enumerating" vs "Sequences"...

Great point; I've kept consistency with "Iterating". 83b5aa4..91052a9

> "es6 (aka ESNext)" AFAIK it's not called either of these things any more. It's ES2015.

I went with "ES6" as the standardization - it's [much more well known than ES2015](https://www.google.com.au/trends/explore#q=es6%2C%20es2015%2C%20ecmascript%206&cmpt=q&tz=): ba91a17

> "Complete the following boilerplate" Maybe be more explicit: "copy this boilerplate to a new file and complete with your solution:"

Much nicer, thanks! 9d29ec6

### 1. Traditional Looping

> Not sure the purpose of [the Traditional Looping] exercise. [...] The `Array` section could be more meaty. [...] If someone needs to be taught about `forEach` vs `for` [...]

Overall, I agree: this lesson is too simplistic, and may drive away more users than it attracts to the workshop. I've nuked it, and distributed the useful bits between other lessons: e3b82cd

### 2. Introduction To Iterators

> What do you mean by "finally" [...] Consider a line break after [...] syntax is likely unfamiliar to many [...] best to not assume what the reader is thinking [...] Note that real-world iterators often throw away the `value` when `done` is true.

Thanks for pointing these out. Fixed in 14eac10

> [...] just give them an object hash, since it's trivial and maybe drives home the point that "Iterators" are just POJOs with a particular flavour of `next`.

Agreed: simplification is always the best option: 81ec4e0

> I ignored the bonus points, don't want to be known as "[teacher's pet](http://www.urbandictionary.com/define.php?term=Teacher%27s+pet&defid=7097197)"

Haha, your call :)

### 3. Built In Iterators

> I believe "Built In" should be hyphenated when used as an adjective.

Awesome, never knew about [compound adjectives](http://www.getitwriteonline.com/archive/040201hyphadj.htm) before now. Thanks for pointing it out. 3a23eda

> "have an iterator" and "provide built in iterators" isn't really right, more correct would be "implements Iterable interface".

Yep, consistency is key: c786b18

> Might be worth introducing [well-known Symbols](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Well-known_symbols)

Added in 182c504

> Objects don't [provide iterators], but `TypedArray` does.

Thanks! 7833c2a

> "not to be confused with looping over objects" -> "not to be confused with looping over objects values with for...in"
> `for(... in ...){}`: I suggest standardising on [MDN syntax of `for...in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

Yep, I caught these in a couple earlier fixes, thanks for pointing them out.

### 4. Advanced Iterables

> "Iteratabls specificatoin:"
> "ie;" [i.e.](http://en.wiktionary.org/wiki/i.e.)

Spelling fixes in 82b9a4e

> [...] it wasn't Iterable itself
> Perhaps also try to encourage understanding that the Iterator interface can and should be used to represent _any_ type of sequence

Great clarification, I've added it in f162a93

> [the `done` key is optional and considered `false` if non-existent](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-iteratorresult-interface).

Thanks for pointing that out. 0b7147a

> `var num, done = false;` IMO manually hoisting variables is an unnecessary anachronism

Fair call. I've fallen into this pattern due to working with devs who are less familiar with how hoisting works. This is the only way to ensure subtle hoisting bugs are avoided. I'm still on the fence about its usefulness, but I figure it can't hurt, and unused variables can optimised away during compile time.

---

> I may have lots of comments but I do this is a great-looking workshop! I can see where you're going with these exercises and I like it. It's nice and gentle. You explain the concepts well, in a good sequence + link to all the appropriate information. Great job!

Thanks mate - really really appreciate your feedback and help! :)
